# Generated by Django 4.1.1 on 2022-10-22 19:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120, unique=True)),
                ('max_time_matches', models.PositiveIntegerField()),
                ('num_time_matches_weight', models.PositiveIntegerField()),
                ('num_matches_weight', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='TimeAvailability',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.CharField(choices=[('1', 'Monday'), ('2', 'Tuesday'), ('3', 'Wednesday'), ('4', 'Thursday'), ('5', 'Friday'), ('6', 'Saturday'), ('7', 'Sunday')], max_length=1)),
                ('time', models.TimeField()),
            ],
            options={
                'unique_together': {('day', 'time')},
            },
        ),
        migrations.CreateModel(
            name='SurveySubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('max_matches', models.PositiveIntegerField()),
                ('name', models.CharField(max_length=50)),
                ('type_of_person', models.CharField(choices=[('1', 'Mentor'), ('2', 'Mentee'), ('3', 'Buddy'), ('4', 'Guide Lifter'), ('5', 'Learner Lifter')], max_length=1)),
                ('power_lifting', models.BooleanField(default=False)),
                ('body_building', models.BooleanField(default=False)),
                ('olympic_lifting', models.BooleanField(default=False)),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('B', 'Non Binary')], max_length=1)),
                ('gender_preference', models.CharField(choices=[('1', 'Same'), ('2', 'All')], max_length=1)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='VandyLifts.organization')),
                ('time_availability', models.ManyToManyField(to='VandyLifts.timeavailability')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='organization',
            name='members',
            field=models.ManyToManyField(through='VandyLifts.SurveySubmission', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='organization',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owner_set', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='organization',
            name='time_choices',
            field=models.ManyToManyField(to='VandyLifts.timeavailability'),
        ),
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('confirmed', models.BooleanField(default=False)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='VandyLifts.organization')),
                ('people', models.ManyToManyField(to='VandyLifts.surveysubmission')),
            ],
        ),
    ]
